services:
  yhys-calendar:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    container_name: yhys-calendar
    restart: unless-stopped
    ports:
      - "3000:3000" # Map API port
    environment:
      - NODE_ENV=production
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: yhys-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yhys_calendar
    volumes:
      - mysql_data:/var/lib/mysql
    # Platform flag helps with compatibility on some architectures (e.g. M1/M2)
    # forcing linux/amd64 is often safer for mysql:5.7
    platform: linux/amd64

volumes:
  mysql_data:


